import { describe, expect, it } from "vitest";
import { buildHandoffPrompt, type HandoffText } from "../src/handoff";
import { buildCitations, versionName } from "../src/citation";
import type { Message } from "../src/export-builders";
import { NOTE_CLOSE, NOTE_OPEN } from "../src/source-notes";

const TEXT: HandoffText = {
  intro: "Here is a conversation. Continue it.",
  start: "=== Conversation ===",
  end: "=== End ===",
  omitted: "{{count}} earlier messages left out",
  user: "User",
  assistant: "Assistant",
};

const CHAT: Message[] = [
  { id: "1", role: "user", order: 0, content: "How do I cook rice?" },
  {
    id: "2",
    role: "assistant",
    order: 1,
    content: `Rinse it first${NOTE_OPEN}1${NOTE_CLOSE}.`,
    thinking: "Hidden reasoning",
    sources: [{ title: "Guide", url: "https://rice.example/" }],
  },
];

describe("buildHandoffPrompt", () => {
  it("frames the conversation as plain text, without thinking", () => {
    expect(buildHandoffPrompt(CHAT, TEXT)).toBe(
      [
        "Here is a conversation. Continue it.",
        "",
        "=== Conversation ===",
        "",
        "User:\nHow do I cook rice?\n\nAssistant:\nRinse it first[1].",
        "",
        "=== End ===",
      ].join("\n"),
    );
  });

  it("keeps the first question and the latest messages of a long chat", () => {
    const long: Message[] = Array.from({ length: 10 }, (_, index) => ({
      id: String(index),
      role: index % 2 === 0 ? "user" : "assistant",
      order: index,
      content: `Message ${index} ${"x".repeat(100)}`,
    }));
    const prompt = buildHandoffPrompt(long, TEXT, 600);

    expect(prompt.length).toBeLessThanOrEqual(600);
    expect(prompt).toContain("Message 0 ");
    expect(prompt).toContain("Message 9 ");
    expect(prompt).not.toContain("Message 1 ");
    expect(prompt).toMatch(/\[\d earlier messages left out\]/);
  });
});

describe("buildCitations", () => {
  const time = new Date(2026, 9, 3, 14, 5).getTime();
  const chat: Message[] = [
    { id: "1", role: "user", order: 0, content: "Explain **photosynthesis** to a ten year old in simple words please, with examples." },
    { id: "2", role: "assistant", order: 1, content: "Plants make food.", time, model: "gpt-4o" },
  ];

  it("writes APA, MLA and Chicago references", () => {
    expect(buildCitations(chat, "https://chatgpt.com/c/abc")).toEqual({
      apa: "OpenAI. (2026). ChatGPT (GPT-4o version) [Large language model]. https://chatgpt.com/c/abc",
      mla: '"Explain photosynthesis to a ten year old in simple words please, with..." prompt. ChatGPT, GPT-4o version, OpenAI, 3 Oct. 2026, chatgpt.com/c/abc.',
      chicago: "Text generated by ChatGPT (GPT-4o), OpenAI, October 3, 2026, https://chatgpt.com/c/abc.",
    });
  });

  it("names each site's maker and leaves out what it doesn't know", () => {
    const now = new Date(2026, 4, 9);
    const citations = buildCitations(
      [{ id: "1", role: "user", order: 0, content: "Hi" }],
      "https://www.kimi.com/chat/abcdefghij",
      now,
    );

    expect(citations.apa).toBe("Moonshot AI. (2026). Kimi [Large language model]. https://www.kimi.com/chat/abcdefghij");
    expect(citations.mla).toBe('"Hi" prompt. Kimi, Moonshot AI, 9 May 2026, www.kimi.com/chat/abcdefghij.');
  });

  it("writes model names as versions", () => {
    expect(versionName("gpt-4o")).toBe("GPT-4o");
    expect(versionName("gpt-5-thinking")).toBe("GPT-5 Thinking");
    expect(versionName("o3-mini")).toBe("o3 mini");
    expect(versionName("claude-sonnet-4-5")).toBe("Claude Sonnet 4.5");
    expect(versionName("Gemini 3.8 Flash")).toBe("Gemini 3.8 Flash");
  });
});
