/*
 * =========================================================
 * AI Exporter - citation.ts
 * =========================================================
 *
 * "Cite this chat": the chat as a reference in APA (7th edition),
 * MLA (9th) and Chicago (17th, a note), the three styles schools
 * and universities ask students to cite AI tools in. The forms
 * follow the styles' own guidance for generative AI:
 *
 *   APA      OpenAI. (2026). ChatGPT (GPT-4o version) [Large
 *            language model]. https://chatgpt.com/c/...
 *   MLA      "Explain photosynthesis" prompt. ChatGPT, GPT-4o
 *            version, OpenAI, 3 Oct. 2026, chatgpt.com/c/....
 *   Chicago  Text generated by ChatGPT, OpenAI, October 3, 2026,
 *            https://chatgpt.com/c/....
 *
 * The tool and its maker come from the chat's site, the version
 * from the model the replies name (see message-metadata.ts), the
 * date from the chat's last message - or today - and the prompt
 * MLA quotes from its first question.
 */
import { getChatSite, type ChatSite } from "./chat-sites.ts";
import type { Message } from "./export-builders.ts";

/* Who makes each site's assistant, and what it's called */
const TOOLS: Record<ChatSite, { tool: string; maker: string }> = {
  chatgpt: { tool: "ChatGPT", maker: "OpenAI" },
  claude: { tool: "Claude", maker: "Anthropic" },
  gemini: { tool: "Gemini", maker: "Google" },
  deepseek: { tool: "DeepSeek", maker: "DeepSeek" },
  grok: { tool: "Grok", maker: "xAI" },
  perplexity: { tool: "Perplexity", maker: "Perplexity AI" },
  copilot: { tool: "Copilot", maker: "Microsoft" },
  mistral: { tool: "Le Chat", maker: "Mistral AI" },
  meta: { tool: "Meta AI", maker: "Meta" },
  kimi: { tool: "Kimi", maker: "Moonshot AI" },
  doubao: { tool: "Doubao", maker: "ByteDance" },
  qwen: { tool: "Qwen", maker: "Alibaba Cloud" },
  qianwen: { tool: "Qwen", maker: "Alibaba Cloud" },
  yuanbao: { tool: "Yuanbao", maker: "Tencent" },
  zai: { tool: "Z.ai", maker: "Zhipu AI" },
};

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/* MLA's abbreviations; May, June and July are written out */
const MLA_MONTHS = [
  "Jan.",
  "Feb.",
  "Mar.",
  "Apr.",
  "May",
  "June",
  "July",
  "Aug.",
  "Sept.",
  "Oct.",
  "Nov.",
  "Dec.",
];

export interface Citations {
  apa: string;
  mla: string;
  chicago: string;
}

/*
 * A model's name as the styles write a version: "gpt-4o" ->
 * "GPT-4o", "claude-sonnet-4-5" -> "Claude Sonnet 4.5", "o3" and
 * "Gemini 3.8 Flash" as they are.
 */
export function versionName(model: string): string {
  const capital = (word: string) => word.charAt(0).toUpperCase() + word.slice(1);

  if (/^gpt-/i.test(model)) {
    const [head, ...rest] = model.slice(4).split("-");

    return [`GPT-${head}`, ...rest.map(capital)].join(" ");
  }

  if (/^o\d/.test(model)) {
    return model.replace(/-/g, " ");
  }

  const words: string[] = [];

  for (const word of model.split(/[-_\s]+/).filter(Boolean)) {
    const last = words[words.length - 1];

    // "4-5" is version 4.5
    if (last !== undefined && /^\d+$/.test(word) && /^\d+(?:\.\d+)*$/.test(last)) {
      words[words.length - 1] = `${last}.${word}`;
    } else {
      words.push(capital(word));
    }
  }

  return words.join(" ");
}

/* The prompt MLA quotes: the first question, cut at a dozen words */
function promptQuote(messages: Message[]): string {
  const question = messages.find((message) => message.role === "user")?.content ?? "";
  const words = question
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/[*_`#>[\]]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .split(" ")
    .filter(Boolean);
  const quote = words.slice(0, 12).join(" ").replace(/[.,;:]+$/, "");

  return words.length > 12 ? `${quote}...` : quote;
}

function withoutScheme(url: string): string {
  return url.replace(/^https?:\/\//, "").replace(/\/$/, "");
}

export function buildCitations(
  messages: Message[],
  tabUrl: string | undefined,
  now = new Date(),
): Citations {
  const site = getChatSite(tabUrl);
  const { tool, maker } = site ? TOOLS[site] : { tool: "AI assistant", maker: "" };
  const times = messages
    .map((message) => message.time)
    .filter((time): time is number => typeof time === "number");
  const date = times.length > 0 ? new Date(Math.max(...times)) : now;
  const model = [...messages].reverse().find((message) => message.model)?.model;
  const version = model ? versionName(model) : "";
  const url = tabUrl && /^https?:\/\//.test(tabUrl) ? tabUrl : "";
  const year = date.getFullYear();
  const day = date.getDate();
  const month = date.getMonth();
  const prompt = promptQuote(messages);
  const author = maker || tool;

  const apa = [
    `${author}. (${year}).`,
    `${tool}${version ? ` (${version} version)` : ""} [Large language model].`,
    url,
  ]
    .filter(Boolean)
    .join(" ");
  const mla = [
    prompt ? `"${prompt}" prompt.` : "",
    `${tool},`,
    version ? `${version} version,` : "",
    maker ? `${maker},` : "",
    `${day} ${MLA_MONTHS[month]} ${year}${url ? "," : "."}`,
    url ? `${withoutScheme(url)}.` : "",
  ]
    .filter(Boolean)
    .join(" ");
  const chicago = `Text generated by ${tool}${version ? ` (${version})` : ""}${maker ? `, ${maker}` : ""}, ${MONTHS[month]} ${day}, ${year}${url ? `, ${url}` : ""}.`;

  return { apa, mla, chicago };
}
